/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { NFTVerifier, NFTVerifierInterface } from "../NFTVerifier";

const _abi = [
  {
    type: "function",
    name: "verifyOwnership",
    inputs: [
      {
        name: "nftContract",
        type: "address",
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class NFTVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): NFTVerifierInterface {
    return new utils.Interface(_abi) as NFTVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTVerifier {
    return new Contract(address, _abi, signerOrProvider) as NFTVerifier;
  }
}
