[dependencies]
forge-std = "1.9.2"
vlayer = "0.1.0-nightly-20241202-164f0bc"
"@openzeppelin-contracts" = "5.0.1"

[dependencies.risc0-ethereum]
version = "1.1.4"
url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v1.1.4-soldeer/contracts.zip"

[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[[profile.default.fs_permissions]]
access = "read"
path = "./testdata"

[soldeer]
remappings_generate = false
remappings_regenerate = false
remappings = [
    "openzeppelin-contracts/=dependencies/openzeppelin-contracts/contracts/",
    "forge-std/=dependencies/forge-std/src/"
]
