[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read", path = "./testdata"}]

[dependencies]
forge-std = "1.9.2"
risc0-ethereum = { version = "1.1.4", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v1.1.4-soldeer/contracts.zip" }
vlayer = "0.1.0-nightly-20241202-164f0bc"
openzeppelin-contracts = { url = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", version = "v5.0.1" }

[soldeer]
remappings_generate = false
remappings_regenerate = false
