[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[[profile.default.fs_permissions]]
access = "read"
path = "./testdata"

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.2"
vlayer = "0.1.0-nightly-20241202-164f0bc"

[dependencies.risc0-ethereum]
version = "1.1.4"
url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v1.1.4-soldeer/contracts.zip"

[soldeer]
# Whether soldeer manages remappings
remappings_generate = false
# Whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

remappings = [
    "openzeppelin-contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=dependencies/forge-std/src/"
]

fs_permissions = [{ access = "read", path = "./testdata" }]
